spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/course_registration
    username: root
    password: 1234

  jpa:
    database: mysql
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB

jwt:
  header: Authorization
  secret: bWluc3VuZy1zdWdhbmctc3lzdGVtLXN3LWNvYWNoLXByb2dyYW0tMjAyMy1pdC1uZWVkcy10by1iZS1sb25nLWVub3VnaC10aGlzLWlzLWp3dC1kZW1vLXByb2plY3Q=
  token-validity-in-seconds: 86400

# log
logging:
  level:
    root: debug

